export enum KeyCodes {
	/** ROBLOX USERINPUTTYPE */
	MouseButton1,
	MouseButton2,
	MouseButton3,
	MouseWheel,
	MouseMovement,
	Touch,

	Focus,
	Accelerometer,
	Gyro,
	TextInput,

	InputMethod,

	/** ROBLOX KEYCODES */
	Unknown,
	Backspace,
	Tab,
	Clear,
	Return,
	Pause,
	Escape,
	Space,
	QuotedDouble,
	Hash,
	Dollar,
	Percent,
	Ampersand,
	Quote,
	LeftParenthesis,
	RightParenthesis,
	Asterisk,
	Plus,
	Comma,
	Minus,
	Period,
	Slash,
	Zero,
	One,
	Two,
	Three,
	Four,
	Five,
	Six,
	Seven,
	Eight,
	Nine,
	Colon,
	Semicolon,
	LessThan,
	Equals,
	GreaterThan,
	Question,
	At,
	LeftBracket,
	BackSlash,
	RightBracket,
	Caret,
	Underscore,
	Backquote,
	A,
	B,
	C,
	D,
	E,
	F,
	G,
	H,
	I,
	J,
	K,
	L,
	M,
	N,
	O,
	P,
	Q,
	R,
	S,
	T,
	U,
	V,
	W,
	X,
	Y,
	Z,
	LeftCurly,
	Pipe,
	RightCurly,
	Tilde,
	Delete,
	World0,
	World1,
	World2,
	World3,
	World4,
	World5,
	World6,
	World7,
	World8,
	World9,
	World10,
	World11,
	World12,
	World13,
	World14,
	World15,
	World16,
	World17,
	World18,
	World19,
	World20,
	World21,
	World22,
	World23,
	World24,
	World25,
	World26,
	World27,
	World28,
	World29,
	World30,
	World31,
	World32,
	World33,
	World34,
	World35,
	World36,
	World37,
	World38,
	World39,
	World40,
	World41,
	World42,
	World43,
	World44,
	World45,
	World46,
	World47,
	World48,
	World49,
	World50,
	World51,
	World52,
	World53,
	World54,
	World55,
	World56,
	World57,
	World58,
	World59,
	World60,
	World61,
	World62,
	World63,
	World64,
	World65,
	World66,
	World67,
	World68,
	World69,
	World70,
	World71,
	World72,
	World73,
	World74,
	World75,
	World76,
	World77,
	World78,
	World79,
	World80,
	World81,
	World82,
	World83,
	World84,
	World85,
	World86,
	World87,
	World88,
	World89,
	World90,
	World91,
	World92,
	World93,
	World94,
	World95,
	KeypadZero,
	KeypadOne,
	KeypadTwo,
	KeypadThree,
	KeypadFour,
	KeypadFive,
	KeypadSix,
	KeypadSeven,
	KeypadEight,
	KeypadNine,
	KeypadPeriod,
	KeypadDivide,
	KeypadMultiply,
	KeypadMinus,
	KeypadPlus,
	KeypadEnter,
	KeypadEquals,
	Up,
	Down,
	Right,
	Left,
	Insert,
	Home,
	End,
	PageUp,
	PageDown,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	F13,
	F14,
	F15,
	NumLock,
	CapsLock,
	ScrollLock,
	RightShift,
	LeftShift,
	RightControl,
	LeftControl,
	RightAlt,
	LeftAlt,
	RightMeta,
	LeftMeta,
	LeftSuper,
	RightSuper,
	Mode,
	Compose,
	Help,
	Print,
	SysReq,
	Break,
	Menu,
	Power,
	Euro,
	Undo,
	ButtonX,
	ButtonY,
	ButtonA,
	ButtonB,
	ButtonR1,
	ButtonL1,
	ButtonR2,
	ButtonL2,
	ButtonR3,
	ButtonL3,
	ButtonStart,
	ButtonSelect,
	DPadLeft,
	DPadRight,
	DPadUp,
	DPadDown,
	Thumbstick1,
	Thumbstick2,
}
export const RobloxKeyCode3AMap = {
	/** ROBLOX USERINPUTTYPE */
	[KeyCodes.MouseButton1]: Enum.UserInputType.MouseButton1,
	[KeyCodes.MouseButton2]: Enum.UserInputType.MouseButton2,
	[KeyCodes.MouseButton3]: Enum.UserInputType.MouseButton3,
	[KeyCodes.MouseWheel]: Enum.UserInputType.MouseWheel,
	[KeyCodes.MouseMovement]: Enum.UserInputType.MouseMovement,
	[KeyCodes.Touch]: Enum.UserInputType.Touch,

	[KeyCodes.Focus]: Enum.UserInputType.Focus,
	[KeyCodes.Accelerometer]: Enum.UserInputType.Accelerometer,
	[KeyCodes.Gyro]: Enum.UserInputType.Gyro,
	[KeyCodes.TextInput]: Enum.UserInputType.TextInput,

	[KeyCodes.InputMethod]: Enum.UserInputType.InputMethod,

	/** ROBLOX KEYCODES */
	[KeyCodes.Unknown]: Enum.KeyCode.Unknown,
	[KeyCodes.Backspace]: Enum.KeyCode.Backspace,
	[KeyCodes.Tab]: Enum.KeyCode.Tab,
	[KeyCodes.Clear]: Enum.KeyCode.Clear,
	[KeyCodes.Return]: Enum.KeyCode.Return,
	[KeyCodes.Pause]: Enum.KeyCode.Pause,
	[KeyCodes.Escape]: Enum.KeyCode.Escape,
	[KeyCodes.Space]: Enum.KeyCode.Space,
	[KeyCodes.QuotedDouble]: Enum.KeyCode.QuotedDouble,
	[KeyCodes.Hash]: Enum.KeyCode.Hash,
	[KeyCodes.Dollar]: Enum.KeyCode.Dollar,
	[KeyCodes.Percent]: Enum.KeyCode.Percent,
	[KeyCodes.Ampersand]: Enum.KeyCode.Ampersand,
	[KeyCodes.Quote]: Enum.KeyCode.Quote,
	[KeyCodes.LeftParenthesis]: Enum.KeyCode.LeftParenthesis,
	[KeyCodes.RightParenthesis]: Enum.KeyCode.RightParenthesis,
	[KeyCodes.Asterisk]: Enum.KeyCode.Asterisk,
	[KeyCodes.Plus]: Enum.KeyCode.Plus,
	[KeyCodes.Comma]: Enum.KeyCode.Comma,
	[KeyCodes.Minus]: Enum.KeyCode.Minus,
	[KeyCodes.Period]: Enum.KeyCode.Period,
	[KeyCodes.Slash]: Enum.KeyCode.Slash,
	[KeyCodes.Zero]: Enum.KeyCode.Zero,
	[KeyCodes.One]: Enum.KeyCode.One,
	[KeyCodes.Two]: Enum.KeyCode.Two,
	[KeyCodes.Three]: Enum.KeyCode.Three,
	[KeyCodes.Four]: Enum.KeyCode.Four,
	[KeyCodes.Five]: Enum.KeyCode.Five,
	[KeyCodes.Six]: Enum.KeyCode.Six,
	[KeyCodes.Seven]: Enum.KeyCode.Seven,
	[KeyCodes.Eight]: Enum.KeyCode.Eight,
	[KeyCodes.Nine]: Enum.KeyCode.Nine,
	[KeyCodes.Colon]: Enum.KeyCode.Colon,
	[KeyCodes.Semicolon]: Enum.KeyCode.Semicolon,
	[KeyCodes.LessThan]: Enum.KeyCode.LessThan,
	[KeyCodes.Equals]: Enum.KeyCode.Equals,
	[KeyCodes.GreaterThan]: Enum.KeyCode.GreaterThan,
	[KeyCodes.Question]: Enum.KeyCode.Question,
	[KeyCodes.At]: Enum.KeyCode.At,
	[KeyCodes.LeftBracket]: Enum.KeyCode.LeftBracket,
	[KeyCodes.BackSlash]: Enum.KeyCode.BackSlash,
	[KeyCodes.RightBracket]: Enum.KeyCode.RightBracket,
	[KeyCodes.Caret]: Enum.KeyCode.Caret,
	[KeyCodes.Underscore]: Enum.KeyCode.Underscore,
	[KeyCodes.Backquote]: Enum.KeyCode.Backquote,
	[KeyCodes.A]: Enum.KeyCode.A,
	[KeyCodes.B]: Enum.KeyCode.B,
	[KeyCodes.C]: Enum.KeyCode.C,
	[KeyCodes.D]: Enum.KeyCode.D,
	[KeyCodes.E]: Enum.KeyCode.E,
	[KeyCodes.F]: Enum.KeyCode.F,
	[KeyCodes.G]: Enum.KeyCode.G,
	[KeyCodes.H]: Enum.KeyCode.H,
	[KeyCodes.I]: Enum.KeyCode.I,
	[KeyCodes.J]: Enum.KeyCode.J,
	[KeyCodes.K]: Enum.KeyCode.K,
	[KeyCodes.L]: Enum.KeyCode.L,
	[KeyCodes.M]: Enum.KeyCode.M,
	[KeyCodes.N]: Enum.KeyCode.N,
	[KeyCodes.O]: Enum.KeyCode.O,
	[KeyCodes.P]: Enum.KeyCode.P,
	[KeyCodes.Q]: Enum.KeyCode.Q,
	[KeyCodes.R]: Enum.KeyCode.R,
	[KeyCodes.S]: Enum.KeyCode.S,
	[KeyCodes.T]: Enum.KeyCode.T,
	[KeyCodes.U]: Enum.KeyCode.U,
	[KeyCodes.V]: Enum.KeyCode.V,
	[KeyCodes.W]: Enum.KeyCode.W,
	[KeyCodes.X]: Enum.KeyCode.X,
	[KeyCodes.Y]: Enum.KeyCode.Y,
	[KeyCodes.Z]: Enum.KeyCode.Z,
	[KeyCodes.LeftCurly]: Enum.KeyCode.LeftCurly,
	[KeyCodes.Pipe]: Enum.KeyCode.Pipe,
	[KeyCodes.RightCurly]: Enum.KeyCode.RightCurly,
	[KeyCodes.Tilde]: Enum.KeyCode.Tilde,
	[KeyCodes.Delete]: Enum.KeyCode.Delete,
	[KeyCodes.World0]: Enum.KeyCode.World0,
	[KeyCodes.World1]: Enum.KeyCode.World1,
	[KeyCodes.World2]: Enum.KeyCode.World2,
	[KeyCodes.World3]: Enum.KeyCode.World3,
	[KeyCodes.World4]: Enum.KeyCode.World4,
	[KeyCodes.World5]: Enum.KeyCode.World5,
	[KeyCodes.World6]: Enum.KeyCode.World6,
	[KeyCodes.World7]: Enum.KeyCode.World7,
	[KeyCodes.World8]: Enum.KeyCode.World8,
	[KeyCodes.World9]: Enum.KeyCode.World9,
	[KeyCodes.World10]: Enum.KeyCode.World10,
	[KeyCodes.World11]: Enum.KeyCode.World11,
	[KeyCodes.World12]: Enum.KeyCode.World12,
	[KeyCodes.World13]: Enum.KeyCode.World13,
	[KeyCodes.World14]: Enum.KeyCode.World14,
	[KeyCodes.World15]: Enum.KeyCode.World15,
	[KeyCodes.World16]: Enum.KeyCode.World16,
	[KeyCodes.World17]: Enum.KeyCode.World17,
	[KeyCodes.World18]: Enum.KeyCode.World18,
	[KeyCodes.World19]: Enum.KeyCode.World19,
	[KeyCodes.World20]: Enum.KeyCode.World20,
	[KeyCodes.World21]: Enum.KeyCode.World21,
	[KeyCodes.World22]: Enum.KeyCode.World22,
	[KeyCodes.World23]: Enum.KeyCode.World23,
	[KeyCodes.World24]: Enum.KeyCode.World24,
	[KeyCodes.World25]: Enum.KeyCode.World25,
	[KeyCodes.World26]: Enum.KeyCode.World26,
	[KeyCodes.World27]: Enum.KeyCode.World27,
	[KeyCodes.World28]: Enum.KeyCode.World28,
	[KeyCodes.World29]: Enum.KeyCode.World29,
	[KeyCodes.World30]: Enum.KeyCode.World30,
	[KeyCodes.World31]: Enum.KeyCode.World31,
	[KeyCodes.World32]: Enum.KeyCode.World32,
	[KeyCodes.World33]: Enum.KeyCode.World33,
	[KeyCodes.World34]: Enum.KeyCode.World34,
	[KeyCodes.World35]: Enum.KeyCode.World35,
	[KeyCodes.World36]: Enum.KeyCode.World36,
	[KeyCodes.World37]: Enum.KeyCode.World37,
	[KeyCodes.World38]: Enum.KeyCode.World38,
	[KeyCodes.World39]: Enum.KeyCode.World39,
	[KeyCodes.World40]: Enum.KeyCode.World40,
	[KeyCodes.World41]: Enum.KeyCode.World41,
	[KeyCodes.World42]: Enum.KeyCode.World42,
	[KeyCodes.World43]: Enum.KeyCode.World43,
	[KeyCodes.World44]: Enum.KeyCode.World44,
	[KeyCodes.World45]: Enum.KeyCode.World45,
	[KeyCodes.World46]: Enum.KeyCode.World46,
	[KeyCodes.World47]: Enum.KeyCode.World47,
	[KeyCodes.World48]: Enum.KeyCode.World48,
	[KeyCodes.World49]: Enum.KeyCode.World49,
	[KeyCodes.World50]: Enum.KeyCode.World50,
	[KeyCodes.World51]: Enum.KeyCode.World51,
	[KeyCodes.World52]: Enum.KeyCode.World52,
	[KeyCodes.World53]: Enum.KeyCode.World53,
	[KeyCodes.World54]: Enum.KeyCode.World54,
	[KeyCodes.World55]: Enum.KeyCode.World55,
	[KeyCodes.World56]: Enum.KeyCode.World56,
	[KeyCodes.World57]: Enum.KeyCode.World57,
	[KeyCodes.World58]: Enum.KeyCode.World58,
	[KeyCodes.World59]: Enum.KeyCode.World59,
	[KeyCodes.World60]: Enum.KeyCode.World60,
	[KeyCodes.World61]: Enum.KeyCode.World61,
	[KeyCodes.World62]: Enum.KeyCode.World62,
	[KeyCodes.World63]: Enum.KeyCode.World63,
	[KeyCodes.World64]: Enum.KeyCode.World64,
	[KeyCodes.World65]: Enum.KeyCode.World65,
	[KeyCodes.World66]: Enum.KeyCode.World66,
	[KeyCodes.World67]: Enum.KeyCode.World67,
	[KeyCodes.World68]: Enum.KeyCode.World68,
	[KeyCodes.World69]: Enum.KeyCode.World69,
	[KeyCodes.World70]: Enum.KeyCode.World70,
	[KeyCodes.World71]: Enum.KeyCode.World71,
	[KeyCodes.World72]: Enum.KeyCode.World72,
	[KeyCodes.World73]: Enum.KeyCode.World73,
	[KeyCodes.World74]: Enum.KeyCode.World74,
	[KeyCodes.World75]: Enum.KeyCode.World75,
	[KeyCodes.World76]: Enum.KeyCode.World76,
	[KeyCodes.World77]: Enum.KeyCode.World77,
	[KeyCodes.World78]: Enum.KeyCode.World78,
	[KeyCodes.World79]: Enum.KeyCode.World79,
	[KeyCodes.World80]: Enum.KeyCode.World80,
	[KeyCodes.World81]: Enum.KeyCode.World81,
	[KeyCodes.World82]: Enum.KeyCode.World82,
	[KeyCodes.World83]: Enum.KeyCode.World83,
	[KeyCodes.World84]: Enum.KeyCode.World84,
	[KeyCodes.World85]: Enum.KeyCode.World85,
	[KeyCodes.World86]: Enum.KeyCode.World86,
	[KeyCodes.World87]: Enum.KeyCode.World87,
	[KeyCodes.World88]: Enum.KeyCode.World88,
	[KeyCodes.World89]: Enum.KeyCode.World89,
	[KeyCodes.World90]: Enum.KeyCode.World90,
	[KeyCodes.World91]: Enum.KeyCode.World91,
	[KeyCodes.World92]: Enum.KeyCode.World92,
	[KeyCodes.World93]: Enum.KeyCode.World93,
	[KeyCodes.World94]: Enum.KeyCode.World94,
	[KeyCodes.World95]: Enum.KeyCode.World95,
	[KeyCodes.KeypadZero]: Enum.KeyCode.KeypadZero,
	[KeyCodes.KeypadOne]: Enum.KeyCode.KeypadOne,
	[KeyCodes.KeypadTwo]: Enum.KeyCode.KeypadTwo,
	[KeyCodes.KeypadThree]: Enum.KeyCode.KeypadThree,
	[KeyCodes.KeypadFour]: Enum.KeyCode.KeypadFour,
	[KeyCodes.KeypadFive]: Enum.KeyCode.KeypadFive,
	[KeyCodes.KeypadSix]: Enum.KeyCode.KeypadSix,
	[KeyCodes.KeypadSeven]: Enum.KeyCode.KeypadSeven,
	[KeyCodes.KeypadEight]: Enum.KeyCode.KeypadEight,
	[KeyCodes.KeypadNine]: Enum.KeyCode.KeypadNine,
	[KeyCodes.KeypadPeriod]: Enum.KeyCode.KeypadPeriod,
	[KeyCodes.KeypadDivide]: Enum.KeyCode.KeypadDivide,
	[KeyCodes.KeypadMultiply]: Enum.KeyCode.KeypadMultiply,
	[KeyCodes.KeypadMinus]: Enum.KeyCode.KeypadMinus,
	[KeyCodes.KeypadPlus]: Enum.KeyCode.KeypadPlus,
	[KeyCodes.KeypadEnter]: Enum.KeyCode.KeypadEnter,
	[KeyCodes.KeypadEquals]: Enum.KeyCode.KeypadEquals,
	[KeyCodes.Up]: Enum.KeyCode.Up,
	[KeyCodes.Down]: Enum.KeyCode.Down,
	[KeyCodes.Right]: Enum.KeyCode.Right,
	[KeyCodes.Left]: Enum.KeyCode.Left,
	[KeyCodes.Insert]: Enum.KeyCode.Insert,
	[KeyCodes.Home]: Enum.KeyCode.Home,
	[KeyCodes.End]: Enum.KeyCode.End,
	[KeyCodes.PageUp]: Enum.KeyCode.PageUp,
	[KeyCodes.PageDown]: Enum.KeyCode.PageDown,
	[KeyCodes.F1]: Enum.KeyCode.F1,
	[KeyCodes.F2]: Enum.KeyCode.F2,
	[KeyCodes.F3]: Enum.KeyCode.F3,
	[KeyCodes.F4]: Enum.KeyCode.F4,
	[KeyCodes.F5]: Enum.KeyCode.F5,
	[KeyCodes.F6]: Enum.KeyCode.F6,
	[KeyCodes.F7]: Enum.KeyCode.F7,
	[KeyCodes.F8]: Enum.KeyCode.F8,
	[KeyCodes.F9]: Enum.KeyCode.F9,
	[KeyCodes.F10]: Enum.KeyCode.F10,
	[KeyCodes.F11]: Enum.KeyCode.F11,
	[KeyCodes.F12]: Enum.KeyCode.F12,
	[KeyCodes.F13]: Enum.KeyCode.F13,
	[KeyCodes.F14]: Enum.KeyCode.F14,
	[KeyCodes.F15]: Enum.KeyCode.F15,
	[KeyCodes.NumLock]: Enum.KeyCode.NumLock,
	[KeyCodes.CapsLock]: Enum.KeyCode.CapsLock,
	[KeyCodes.ScrollLock]: Enum.KeyCode.ScrollLock,
	[KeyCodes.RightShift]: Enum.KeyCode.RightShift,
	[KeyCodes.LeftShift]: Enum.KeyCode.LeftShift,
	[KeyCodes.RightControl]: Enum.KeyCode.RightControl,
	[KeyCodes.LeftControl]: Enum.KeyCode.LeftControl,
	[KeyCodes.RightAlt]: Enum.KeyCode.RightAlt,
	[KeyCodes.LeftAlt]: Enum.KeyCode.LeftAlt,
	[KeyCodes.RightMeta]: Enum.KeyCode.RightMeta,
	[KeyCodes.LeftMeta]: Enum.KeyCode.LeftMeta,
	[KeyCodes.LeftSuper]: Enum.KeyCode.LeftSuper,
	[KeyCodes.RightSuper]: Enum.KeyCode.RightSuper,
	[KeyCodes.Mode]: Enum.KeyCode.Mode,
	[KeyCodes.Compose]: Enum.KeyCode.Compose,
	[KeyCodes.Help]: Enum.KeyCode.Help,
	[KeyCodes.Print]: Enum.KeyCode.Print,
	[KeyCodes.SysReq]: Enum.KeyCode.SysReq,
	[KeyCodes.Break]: Enum.KeyCode.Break,
	[KeyCodes.Menu]: Enum.KeyCode.Menu,
	[KeyCodes.Power]: Enum.KeyCode.Power,
	[KeyCodes.Euro]: Enum.KeyCode.Euro,
	[KeyCodes.Undo]: Enum.KeyCode.Undo,
	[KeyCodes.ButtonX]: Enum.KeyCode.ButtonX,
	[KeyCodes.ButtonY]: Enum.KeyCode.ButtonY,
	[KeyCodes.ButtonA]: Enum.KeyCode.ButtonA,
	[KeyCodes.ButtonB]: Enum.KeyCode.ButtonB,
	[KeyCodes.ButtonR1]: Enum.KeyCode.ButtonR1,
	[KeyCodes.ButtonL1]: Enum.KeyCode.ButtonL1,
	[KeyCodes.ButtonR2]: Enum.KeyCode.ButtonR2,
	[KeyCodes.ButtonL2]: Enum.KeyCode.ButtonL2,
	[KeyCodes.ButtonR3]: Enum.KeyCode.ButtonR3,
	[KeyCodes.ButtonL3]: Enum.KeyCode.ButtonL3,
	[KeyCodes.ButtonStart]: Enum.KeyCode.ButtonStart,
	[KeyCodes.ButtonSelect]: Enum.KeyCode.ButtonSelect,
	[KeyCodes.DPadLeft]: Enum.KeyCode.DPadLeft,
	[KeyCodes.DPadRight]: Enum.KeyCode.DPadRight,
	[KeyCodes.DPadUp]: Enum.KeyCode.DPadUp,
	[KeyCodes.DPadDown]: Enum.KeyCode.DPadDown,
	[KeyCodes.Thumbstick1]: Enum.KeyCode.Thumbstick1,
	[KeyCodes.Thumbstick2]: Enum.KeyCode.Thumbstick2,
} satisfies Record<KeyCodes, Enum.KeyCode | Enum.UserInputType>;

export const RobloxKeyCode3AReverseMap = new Map<Enum.KeyCode | Enum.UserInputType, KeyCodes>();

for (const [k, v] of pairs(RobloxKeyCode3AMap)) {
	RobloxKeyCode3AReverseMap.set(v, k);
}
